### ISSUE TITLE
Umbrella genblaze.__getattr__ drops the optional-dependency install hint (regression from #165)

### ISSUE THREAD

**Issue by jeronimodeleon** [backblaze-labs/genblaze#197]
## Summary

The #165 fix taught `genblaze_core.__getattr__` to re-raise `OptionalDependencyError` as `AttributeError` so `hasattr()`/introspection works. But the umbrella `genblaze` package's own `__getattr__` (`libs/meta/genblaze/__init__.py`) was **not** updated to match, and it assumes any `AttributeError` from `_core` means "unknown name". As a result, the actionable `pip install "genblaze[parquet]"` hint is lost for the umbrella package's primary usage pattern — and the fallback message actively misdirects.

## Steps to reproduce

```python
import sys
sys.modules['pyarrow'] = None  # simulate the `parquet` extra not installed
import genblaze

genblaze.ParquetSink
# AttributeError: module 'genblaze' has no attribute 'ParquetSink'.
#   For nested submodules ... For provider adapters, install the connector
#   and import from its own package, e.g. `from genblaze_openai import SoraProvider`
#   after `pip install "genblaze[openai]"`.

from genblaze import ParquetSink
# ImportError: cannot import name 'ParquetSink' from 'genblaze' (.../libs/meta/genblaze/__init__.py)
```

## Expected behavior

Both paths should surface the real, actionable hint: `pip install "genblaze[parquet]"` (the behavior #8/#165 exist to provide). `hasattr(genblaze, "ParquetSink")` should still return `False` (this part works today).

## Actual behavior

- `genblaze.ParquetSink` → misleading message telling the user `ParquetSink` is a **provider adapter** and suggesting `pip install "genblaze[openai]"`. The `genblaze[parquet]` hint is gone.
- `from genblaze import ParquetSink` → bare `ImportError: cannot import name`, hint gone.

`libs/meta/genblaze/__init__.py`'s `__getattr__` catches `AttributeError` from `getattr(_core, name)` and unconditionally rewrites it to the "unknown attribute / provider adapter" message, because it can no longer distinguish "name isn't in `_LAZY_IMPORTS`" from "name is known but its optional dep is missing".

## Impact

Regression from #165, scoped to the **umbrella `genblaze` package** (the dominant install/import surface). It degrades error quality only — a user without the `parquet` extra couldn't use `ParquetSink` regardless — but the misdirection to a connector-install command is worse than the pre-#165 behavior for this path. **P2** (released-behavior regression, no functional loss). `libs/meta/tests/test_shim.py` has no missing-optional-dependency test through the umbrella `__getattr__`, so nothing caught it.

## Suggested fix

Give `genblaze.__getattr__` the same treatment as core's: inspect the caught error's `__cause__` for `OptionalDependencyError` and re-raise preserving `str(cause)` (the install hint) when present; only fall through to the "unknown name / provider adapter" message for genuinely-unknown names. Add a `libs/meta/tests/test_shim.py` case mirroring core's `TestLazyAttributeCapabilityProbing` (both `hasattr` → `False` and direct access → hint preserved).

## References

- #165 — the core-side fix this regresses through the umbrella
- #8 — original optional-dependency install-hint behavior
- `libs/core/genblaze_core/__init__.py:139-160`, `libs/meta/genblaze/__init__.py:45-60`

_Found in a 5-perspective panel review of the v0.6.0 wave (DX lens + Codex native, cross-family consensus; reproduced against installed packages)._
